### ISSUE TITLE
Encoding issue for Cote d'Ivoire

### ISSUE THREAD

**Issue by flesicek** [iERP-ai/businesswithcovid-generator#11]
This line is not corrently mapping cote d'Ivoire

d_name2alpha["Cote d'Ivoire"] = d_name2alpha["Côte d'Ivoire"]

**Comment by tommycarstensen** [comment]
I'm not quite sure how to fix this encoding problem. I can't replicate it, because my system settings are different.

OK, I came up with a fix. I just hard coded it:
`d_name2alpha["Cote d'Ivoire"] = 'CIV'`

I double checked the alpha3 code on Wikipedia:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
